# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Set the branch to trigger the pipeline on
 
pool:
  vmImage: 'windows-latest'  # Use a Windows agent
 
steps:
 
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
 
- script: 'mvn clean test'  # Command to build and run your Selenium tests using Maven
  displayName: 'Run Selenium Tests'
